update pendulum graph
nhatlong1/final_project_physics pull request #6
Opened 2022-06-10 06:04 UTC by phamnam95

Refractor Sáng's code for pendulum with graph.

2022-06-10 07:22 UTC, nhatlong1 commented on pendulum/graph.py
> +matplotlib.use('MacOSX')
Error
```console
ImportError: cannot import name '_macosx' from 'matplotlib.backends'
```

2022-06-10 07:28 UTC, nhatlong1 commented on pendulum/graph.py
> +    #plt.show()
Plot failed to display

2022-06-10 07:32 UTC, nhatlong1 commented on pendulum/main.py
> +    plt.show()
Why

2022-06-10 07:35 UTC, nhatlong1 commented on pendulum/main.py
> +        # Increase gravity
Repeat code outside event loop

2022-06-10 07:36 UTC, nhatlong1 commented on pendulum/button.py
> +		return action
Consider using Button from root `includes` folder

2022-06-10 08:31 UTC, nhatlong1 commented on pendulum/graph.py
> +matplotlib.use('MacOSX')
`matplotlib` version: `3.5.2`

2022-06-10 08:34 UTC, nhatlong1 commented on pendulum/main.py
> +    plt.show()
Because of `graph.py` problem, all I see is a blank and useless window that will crash when focused on or resize.

2022-06-10 08:36 UTC, nhatlong1 requested changes
# Problems
- Messy code
- <b><ins>Can not run properly on my laptop</ins></b> (second comment of `graph.py`)
    OS: Microsoft Windows 10 version 21H2
- Create graph stop pendulum animation and open a blank window
- Changing velocity also shorten pendulum path

# Possible fixes:
- Update `requirements.txt`
- Use non-platform specific functions
- Make your code easier to read first
# Must do:
- STOP USING WRONG RELATIVE PATHS. USE `pathlib` TO HANDLE PATHS
# Suggestions:
- Use more functions.
- Use more files.
- Follow PEP 8 Style Guide.
- Stop using magic numbers
- Use `Button` in root `includes`

2022-06-10 08:36 UTC, nhatlong1 commented on pendulum/main.py
> +
to here

2022-06-10 08:37 UTC, nhatlong1 commented on pendulum/main.py
> +class ball(object):
Put this class into another file

2022-06-10 08:37 UTC, nhatlong1 commented on pendulum/main.py
> +    width, height = 950, 600
This is constants. Change to WIDTH and HEIGHT

2022-06-10 08:46 UTC, nhatlong1 commented on pendulum/button.py
> +	def draw(self, surface):
`draw` supposed to <b>PUT THIS BUTTON ON SCREEN</b> not <b>CHECK FOR CLICK</b>

2022-06-10 08:47 UTC, nhatlong1 commented on pendulum/main.py
> +        background.blit(pygame.transform.scale(
Useless extra lines of code because wrong implementation of `draw()` function

2022-06-10 08:48 UTC, nhatlong1 commented on pendulum/main.py
> +        if graph_check == True:
This should be a function

2022-06-10 08:49 UTC, nhatlong1 commented on pendulum/main.py
> +
To here

2022-06-10 08:49 UTC, nhatlong1 commented on pendulum/main.py
> +        coordinates = 'coordinates.txt'
CONSTANT

2022-06-10 08:49 UTC, nhatlong1 commented on pendulum/main.py
> +        times = 'times.txt'
CONSTANT

2022-06-10 08:50 UTC, nhatlong1 commented on pendulum/main.py
> +        t.close()
Useless

2022-06-10 08:50 UTC, nhatlong1 commented on pendulum/main.py
> +        c.close()
Useless

2022-06-10 08:52 UTC, nhatlong1 commented on pendulum/main.py
> +            elif check_click == 0:
????

2022-06-10 08:56 UTC, nhatlong1 commented on pendulum/main.py
> +        clock.tick(120)
30-60 is enough. Don't increase framerate because your pendulum is slow. INCREASE THE BASE SPEED.
Higher FPS use more CPU power. Increase speed to make pendulum swing faster does not consume more CPU power

2022-06-10 08:57 UTC, nhatlong1 commented on pendulum/main.py
> +        check_click = 0
Useless

2022-06-10 09:00 UTC, nhatlong1 commented on pendulum/main.py
> +    gravity_img = pygame.image.load(r'assets/velocity.png').convert()
Fix your button's `draw()` method and remove these useless variables. Load directly in Button
```python
a = Button(0, 0, pygame.image.load("assets/plus.png"), 1)
```

2022-06-10 09:02 UTC, nhatlong1 commented on pendulum/main.py
> +    background2 = background2.convert_alpha()
`convert_alpha()` directly on previous line. `convert_alpha` also return a `Surface`

2022-06-10 09:03 UTC, nhatlong1 commented on pendulum/main.py
> +    background = pygame.display.set_mode((width, height))
This should be `screen` or `surface`. Not `background`.

2022-06-10 09:03 UTC, nhatlong1 commented on pendulum/main.py
> +                    background2 = pygame.Surface([width, height],
Repeat?

2022-06-10 09:13 UTC, nhatlong1 commented on pendulum/main.py
> +    main()
Also, remove all prints and useless file writing part after you've done debugging. No one need some extra meaningless text files when running your code

2022-06-10 22:06 UTC, phamnam95 commented on pendulum/graph.py
> +    #plt.show()
The graph.py only process the txt files of coordinates and time to produce 2 arrays. It does not produce plot. The plotting commands are commented and will be removed.

2022-06-10 22:07 UTC, phamnam95 commented on pendulum/main.py
> +    plt.show()
These lines are to produce a blank window that will show the graph in real time when you click on the graph button.

2022-06-10 22:08 UTC, phamnam95 commented on pendulum/main.py
> +        # Increase gravity
Agree. Can change these lines to a function.

2022-06-10 22:08 UTC, phamnam95 commented on pendulum/button.py
> +		return action
Agree

2022-06-10 22:09 UTC, phamnam95 commented on pendulum/graph.py
> +matplotlib.use('MacOSX')
will be deleted

2022-06-10 22:09 UTC, phamnam95 commented on pendulum/main.py
> +class ball(object):
Agree

2022-06-10 22:09 UTC, phamnam95 commented on pendulum/main.py
> +    width, height = 950, 600
Agree

2022-06-10 22:10 UTC, phamnam95 commented on pendulum/button.py
> +	def draw(self, surface):
Agree. Put draw in one function and check for click in another function.

2022-06-10 22:11 UTC, phamnam95 commented on pendulum/main.py
> +        background.blit(pygame.transform.scale(
It can be put inside draw function of the pendulum. But then the draw function will need more inputs of images for buttons and background.

2022-06-10 22:12 UTC, phamnam95 commented on pendulum/main.py
> +        if graph_check == True:
Agree

2022-06-10 22:12 UTC, phamnam95 commented on pendulum/main.py
> +        t.close()
Can think of different way to process the data and draw without the need to save in txt files.

2022-06-10 22:14 UTC, phamnam95 commented on pendulum/main.py
> +            elif check_click == 0:
The reason for check_click is that if you click on any regions of the background, it will create a new pendulum. Therefore, it need to be checked. Or we can think of other workaround.

2022-06-10 22:14 UTC, phamnam95 commented on pendulum/main.py
> +        clock.tick(120)
Agree

2022-06-10 22:15 UTC, phamnam95 commented on pendulum/main.py
> +    gravity_img = pygame.image.load(r'assets/velocity.png').convert()
Agree

2022-06-10 22:15 UTC, phamnam95 commented on pendulum/main.py
> +    background2 = background2.convert_alpha()
Agree

2022-06-10 22:15 UTC, phamnam95 commented on pendulum/main.py
> +    background = pygame.display.set_mode((width, height))
Agree

2022-06-10 22:16 UTC, phamnam95 commented on pendulum/main.py
> +                    background2 = pygame.Surface([width, height],
The reason for repeating is to delete the pendulum path of previous run. Otherwise, when you create a new pendulum, old path will be still there. Need to think of a workaround.

2022-06-10 22:16 UTC, phamnam95 commented on pendulum/main.py
> +    main()
Agree

2022-06-11 04:20 UTC, phamnam95 commented on pendulum/graph.py
> +import matplotlib.pyplot as plt
will be deleted

2022-06-11 04:22 UTC, nhatlong1 commented on pendulum/main.py
> +    gravity_img = pygame.image.load(r'assets/velocity.png').convert()
![image](https://user-images.githubusercontent.com/83014004/173172163-7a269406-e8f0-4b48-84e7-7d1f91747013.png)

See? Problem with relative paths. Is this thing will not work anywhere else than in it own directory.
Use this instead
```python
from pathlib import Path

asset = pygame.image.load(rf"{Path(__file__).parent}\assets\plus.png")
```
This is what I always use when I need to load resources. Unless it's a CLI app and requires user to provide the resource  at any location that app is executed, <b><ins>NEVER USE RELATIVE PATHS</ins></b>

2022-06-11 04:26 UTC, phamnam95 commented on pendulum/main.py
> +    gravity_img = pygame.image.load(r'assets/velocity.png').convert()
Agree

2022-06-11 04:31 UTC, nhatlong1 commented on pendulum/graph.py
> +    for line in lines:
There's only 1 line
```python
with open(coordinates, 'w') as c:
            c.write(' '.join(arr_X))
```
This piece of code basically join everything inside that list/tuple into a <b>single</b> string, and <b>overwrite</b> said file with that string, this line is not needed

2022-06-11 04:31 UTC, nhatlong1 commented on pendulum/graph.py
> +        temp_1.append((line.split(' ')))
Splitting return a list. So just split. There's only 1 line. No need to append anything

2022-06-11 04:34 UTC, nhatlong1 commented on pendulum/graph.py
> +    for i in range(len(temp_1)):
And this will be
```python
position_x = [int(i) for i in temp_1]
```

2022-06-11 04:37 UTC, nhatlong1 commented on pendulum/graph.py
> +    del position_y[len(position_x):]
```python
position_y = position_y[:len(position_x)]
```
This will keep everything from index 0 to index len(position_x)

2022-06-11 04:44 UTC, nhatlong1 commented on pendulum/graph.py
> +    #plt.show()
Also, you <b>DON'T CLOSE THE FILE WHERE CLOSE IS NEEDED</b>
Using plain open and no close? While closing file managed by the <b>context manager</b> and <b>automatically</b> closed?

2022-06-11 04:53 UTC, nhatlong1 commented on pendulum/graph.py
> +    #plt.show()
```python
def coordinates_process():
    try:
        coordinates = open('coordinates.txt')
        lines = coordinates.read()
    except Exception:
        coordinates.close()
    finally:
        if not lines:
            temp_1 = []
        else:
            temp_1 = [i.strip() for i in lines.split(" ")]
        coordinates.close()

    try:
        count = open('times.txt')
        line_count = count.read()
    except Exception:
        count.close()
    finally:
        if not line_count:
            temp_2 = []
        else:
            temp_2 = [i.strip() for i in line_count.split(' ')]
        count.close()

    if not temp_1 or not temp_2:
        return (), ()

    position_x = [int(i) for i in temp_1]
    position_y = [int(i) for i in temp_2[:len(temp_1)]]
    return position_x, position_y


print(coordinates_process())
```
New graph.py. Remove the last print statement.

2022-06-11 04:56 UTC, phamnam95 commented on pendulum/graph.py
> +    #plt.show()
Can you run the graph on your machine now?

2022-06-11 07:32 UTC, nhatlong1 commented on pendulum/main.py
> +            elif check_click == 0:
Possible solution:
Create a rectangle (`pygame.Rect`) around all buttons and labels. Then for every `MOUSEBUTTONDOWN` event, check for collision using `rect.collidepoint()`. If return is False, run code, else ignore it

2022-06-11 07:33 UTC, nhatlong1 commented on pendulum/main.py
> +        t.close()
Because this is basically a string, add 2 arguments to process function, then pass 2 string directly to that function

2022-06-11 07:34 UTC, nhatlong1 commented on pendulum/graph.py
> +    #plt.show()
New graph.py
```python
def coordinates_process(lines, count):
    if not lines:
        temp_1 = []
    else:
        temp_1 = [i.strip() for i in lines.split(" ")]

    if not count:
        temp_2 = []
    else:
        temp_2 = [i.strip() for i in count.split(' ')]

    if not temp_1 or not temp_2:
        return (), ()

    position_x = [int(i) for i in temp_1]
    position_y = [int(i) for i in temp_2[:len(temp_1)]]
    return position_x, position_y
```

2022-06-11 09:02 UTC, nhatlong1 commented on pendulum/includes/button.py
> +"""Button
A slightly changed version of root's includes/button.py. Add a small experimental feature

2022-06-11 09:02 UTC, nhatlong1 commented on pendulum/includes/object.py
> +    def __init__(self, coords: list | tuple = ..., radius: int = ..., balance: int = ...):
Renamed XY to coords

2022-06-11 09:03 UTC, nhatlong1 commented on pendulum/includes/object.py
> +    def draw(self, screen: pygame.Surface, click_region: pygame.Surface,
Forcing `str` type for color and HEX for format

2022-06-11 09:05 UTC, nhatlong1 commented on pendulum/main.py
> +        self.__button_font = pygame.font.SysFont("times new roman", 40)
Probably better to use `pygame.font.Font` and load a font from `.ttf` file instead. But "times new roman" should be available on most computers

2022-06-11 09:05 UTC, nhatlong1 commented on pendulum/main.py
> +        self.__background = pygame.image.load(rf"{Path(__file__).parent}"
No more relative paths @Gnas23

2022-06-11 09:06 UTC, nhatlong1 commented on pendulum/main.py
> +    def draw_graph(self):
I don't really know how to use matplotlib, so I remove subplots and only use basic plotting

2022-06-11 09:07 UTC, nhatlong1 commented on pendulum/main.py
> +        if self.__acceleration:
As this is a bool type variable, probably I will add a feature to remove the pendulum or pause the pendulum's movement.

2022-06-11 09:09 UTC, nhatlong1 commented on pendulum/main.py
> +    def reset_region(self):
Added because `__click_region` is re-defined more than once

2022-06-11 09:11 UTC, nhatlong1 commented on pendulum/main.py
> +                    if not self.__exception_region.collidepoint(mouse_pos):
Collision check using a Rect

2022-06-11 09:13 UTC, nhatlong1 reviewed
@phamnam95 @nhatlong1 Please review my changes

2022-06-22 13:11 UTC, nhatlong1 approved these changes

2022-06-22 13:12 UTC, merged